"""versao_inicial

Revision ID: 0001
Revises: 
Create Date: 2026-03-26 12:30:05.415253

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artigos_phc',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('referencia', sa.String(length=50), nullable=False),
    sa.Column('designacao', sa.String(length=300), nullable=True),
    sa.Column('stock_atual', sa.Float(), nullable=True),
    sa.Column('preco_custo', sa.Float(), nullable=True),
    sa.Column('preco_custo_ponderado', sa.Float(), nullable=True),
    sa.Column('unidade', sa.String(length=20), nullable=True),
    sa.Column('familia', sa.String(length=100), nullable=True),
    sa.Column('taxa_iva', sa.Float(), nullable=True),
    sa.Column('ultima_sync', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('artigos_phc', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_artigos_phc_referencia'), ['referencia'], unique=True)

    op.create_table('config_ia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=True),
    sa.Column('lm_host', sa.String(length=100), nullable=True),
    sa.Column('lm_port', sa.Integer(), nullable=True),
    sa.Column('lm_model', sa.String(length=200), nullable=True),
    sa.Column('claude_api_key', sa.String(length=200), nullable=True),
    sa.Column('ultimo_teste', sa.DateTime(), nullable=True),
    sa.Column('teste_ok', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('config_phc',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('servidor', sa.String(length=200), nullable=True),
    sa.Column('porta', sa.Integer(), nullable=True),
    sa.Column('base_dados', sa.String(length=100), nullable=True),
    sa.Column('autenticacao', sa.String(length=20), nullable=True),
    sa.Column('utilizador', sa.String(length=100), nullable=True),
    sa.Column('password', sa.String(length=200), nullable=True),
    sa.Column('ultima_sync', sa.DateTime(), nullable=True),
    sa.Column('sync_auto', sa.Boolean(), nullable=True),
    sa.Column('sync_hora', sa.String(length=5), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fornecedores_phc',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=True),
    sa.Column('nif', sa.String(length=20), nullable=True),
    sa.Column('morada', sa.String(length=300), nullable=True),
    sa.Column('localidade', sa.String(length=100), nullable=True),
    sa.Column('cod_postal', sa.String(length=20), nullable=True),
    sa.Column('telefone', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('ultima_sync', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fornecedores_phc', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fornecedores_phc_numero'), ['numero'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('departamento', sa.String(length=100), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('pedidos_compra',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('departamento', sa.String(length=100), nullable=True),
    sa.Column('prioridade', sa.String(length=20), nullable=True),
    sa.Column('estado', sa.String(length=30), nullable=True),
    sa.Column('criado_por', sa.Integer(), nullable=True),
    sa.Column('aprovado_por', sa.Integer(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('data_aprovacao', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['aprovado_por'], ['users.id'], ),
    sa.ForeignKeyConstraint(['criado_por'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('linhas_pedido',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pedido_id', sa.Integer(), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=True),
    sa.Column('artigo_ref', sa.String(length=50), nullable=True),
    sa.Column('referencia', sa.String(length=50), nullable=True),
    sa.Column('designacao', sa.String(length=300), nullable=True),
    sa.Column('unidade', sa.String(length=20), nullable=True),
    sa.Column('quantidade', sa.Float(), nullable=True),
    sa.Column('stock_atual', sa.Float(), nullable=True),
    sa.Column('preco_custo_ref', sa.Float(), nullable=True),
    sa.Column('preco_pcp_ref', sa.Float(), nullable=True),
    sa.Column('fornecedor_hab', sa.String(length=200), nullable=True),
    sa.Column('observacoes', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedidos_compra.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('linhas_pedido', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_linhas_pedido_artigo_ref'), ['artigo_ref'], unique=False)

    op.create_table('orcamentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pedido_id', sa.Integer(), nullable=False),
    sa.Column('empresa', sa.String(length=200), nullable=True),
    sa.Column('nif', sa.String(length=20), nullable=True),
    sa.Column('numero_orcamento', sa.String(length=50), nullable=True),
    sa.Column('contacto', sa.String(length=200), nullable=True),
    sa.Column('data_orcamento', sa.Date(), nullable=True),
    sa.Column('validade', sa.Date(), nullable=True),
    sa.Column('subtotal', sa.Float(), nullable=True),
    sa.Column('desconto_total', sa.Float(), nullable=True),
    sa.Column('desconto_percentagem', sa.Float(), nullable=True),
    sa.Column('iva_valor', sa.Float(), nullable=True),
    sa.Column('total', sa.Float(), nullable=True),
    sa.Column('moeda', sa.String(length=10), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('ficheiro_pdf', sa.String(length=300), nullable=True),
    sa.Column('dados_brutos', sa.Text(), nullable=True),
    sa.Column('selecionado', sa.Boolean(), nullable=True),
    sa.Column('carregado_por', sa.Integer(), nullable=True),
    sa.Column('data_upload', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['carregado_por'], ['users.id'], ),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedidos_compra.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('items_orcamento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('orcamento_id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(length=500), nullable=True),
    sa.Column('referencia', sa.String(length=100), nullable=True),
    sa.Column('quantidade', sa.Float(), nullable=True),
    sa.Column('unidade', sa.String(length=20), nullable=True),
    sa.Column('preco_unitario', sa.Float(), nullable=True),
    sa.Column('desconto_item', sa.Float(), nullable=True),
    sa.Column('total_item', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['orcamento_id'], ['orcamentos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('items_orcamento')
    op.drop_table('orcamentos')
    with op.batch_alter_table('linhas_pedido', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_linhas_pedido_artigo_ref'))

    op.drop_table('linhas_pedido')
    op.drop_table('pedidos_compra')
    op.drop_table('users')
    with op.batch_alter_table('fornecedores_phc', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fornecedores_phc_numero'))

    op.drop_table('fornecedores_phc')
    op.drop_table('config_phc')
    op.drop_table('config_ia')
    with op.batch_alter_table('artigos_phc', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_artigos_phc_referencia'))

    op.drop_table('artigos_phc')
    # ### end Alembic commands ###
