"""config_reposicao

Revision ID: 0004
Revises: 0003
Create Date: 2026-03-30 08:57:54.907061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0004'
down_revision = '0003'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('config_reposicao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('artigo_ref', sa.String(length=50), nullable=True),
    sa.Column('meses_historico', sa.Integer(), nullable=True),
    sa.Column('lead_time_dias', sa.Float(), nullable=True),
    sa.Column('fator_seguranca', sa.Float(), nullable=True),
    sa.Column('meses_cobertura', sa.Integer(), nullable=True),
    sa.Column('custo_encomenda', sa.Float(), nullable=True),
    sa.Column('taxa_posse_anual', sa.Float(), nullable=True),
    sa.Column('quantidade_minima_encomenda', sa.Float(), nullable=True),
    sa.Column('alertar_dias_cobertura', sa.Integer(), nullable=True),
    sa.Column('ignorar_parados_dias', sa.Integer(), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.Column('atualizado_por', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['atualizado_por'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('config_reposicao', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_config_reposicao_artigo_ref'), ['artigo_ref'], unique=False)


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('config_reposicao', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_config_reposicao_artigo_ref'))

    op.drop_table('config_reposicao')
    # ### end Alembic commands ###
