"""pending_matches

Revision ID: 0005
Revises: 0004
Create Date: 2026-03-30 10:38:06.471959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0005'
down_revision = '0004'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pending_matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pedido_id', sa.Integer(), nullable=False),
    sa.Column('orcamento_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('descricao_forn', sa.String(length=500), nullable=True),
    sa.Column('referencia_forn', sa.String(length=100), nullable=True),
    sa.Column('fornecedor', sa.String(length=200), nullable=True),
    sa.Column('artigo_ref_sugerido', sa.String(length=50), nullable=True),
    sa.Column('confianca_sugerido', sa.Float(), nullable=True),
    sa.Column('metodo', sa.String(length=30), nullable=True),
    sa.Column('confirmado', sa.Boolean(), nullable=True),
    sa.Column('artigo_ref_final', sa.String(length=50), nullable=True),
    sa.Column('confirmado_por', sa.Integer(), nullable=True),
    sa.Column('data_confirmacao', sa.DateTime(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['confirmado_por'], ['users.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['items_orcamento.id'], ),
    sa.ForeignKeyConstraint(['orcamento_id'], ['orcamentos.id'], ),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedidos_compra.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_table('pending_matches')
    # ### end Alembic commands ###
