"""clientes_embarcacoes_config_geral

Revision ID: 0006
Revises: 0005
Create Date: 2026-03-30 10:56:02.513441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0006'
down_revision = '0005'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phc_no', sa.Integer(), nullable=True),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('abreviatura', sa.String(length=50), nullable=True),
    sa.Column('nif', sa.String(length=20), nullable=True),
    sa.Column('morada', sa.String(length=300), nullable=True),
    sa.Column('localidade', sa.String(length=100), nullable=True),
    sa.Column('cod_postal', sa.String(length=20), nullable=True),
    sa.Column('pais', sa.String(length=50), nullable=True),
    sa.Column('telefone', sa.String(length=50), nullable=True),
    sa.Column('telemovel', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('website', sa.String(length=200), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.Column('ultima_sync_phc', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clientes_phc_no'), ['phc_no'], unique=True)

    op.create_table('config_geral',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_nome', sa.String(length=200), nullable=True),
    sa.Column('empresa_abrev', sa.String(length=50), nullable=True),
    sa.Column('empresa_nif', sa.String(length=20), nullable=True),
    sa.Column('empresa_morada', sa.String(length=300), nullable=True),
    sa.Column('empresa_tel', sa.String(length=50), nullable=True),
    sa.Column('empresa_email', sa.String(length=150), nullable=True),
    sa.Column('empresa_logo_path', sa.String(length=300), nullable=True),
    sa.Column('cor_accent', sa.String(length=7), nullable=True),
    sa.Column('cor_bg', sa.String(length=7), nullable=True),
    sa.Column('cor_surface', sa.String(length=7), nullable=True),
    sa.Column('tema_nome', sa.String(length=50), nullable=True),
    sa.Column('backup_local_path', sa.String(length=500), nullable=True),
    sa.Column('backup_rede_path', sa.String(length=500), nullable=True),
    sa.Column('backup_hora', sa.String(length=5), nullable=True),
    sa.Column('backup_manter_dias', sa.Integer(), nullable=True),
    sa.Column('backup_auto_ativo', sa.Boolean(), nullable=True),
    sa.Column('ultimo_backup', sa.DateTime(), nullable=True),
    sa.Column('ultimo_backup_ok', sa.Boolean(), nullable=True),
    sa.Column('claude_chat_ativo', sa.Boolean(), nullable=True),
    sa.Column('claude_chat_sistema', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('embarcacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('matricula', sa.String(length=50), nullable=True),
    sa.Column('tipo', sa.String(length=100), nullable=True),
    sa.Column('ano_construcao', sa.Integer(), nullable=True),
    sa.Column('comprimento', sa.Float(), nullable=True),
    sa.Column('largura', sa.Float(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('componentes_embarcacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('embarcacao_id', sa.Integer(), nullable=False),
    sa.Column('categoria', sa.String(length=100), nullable=True),
    sa.Column('label', sa.String(length=200), nullable=True),
    sa.Column('marca', sa.String(length=100), nullable=True),
    sa.Column('modelo', sa.String(length=100), nullable=True),
    sa.Column('num_serie', sa.String(length=100), nullable=True),
    sa.Column('ano', sa.Integer(), nullable=True),
    sa.Column('campos_extra', sa.Text(), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('ordem', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['embarcacao_id'], ['embarcacoes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_table('componentes_embarcacao')
    op.drop_table('embarcacoes')
    op.drop_table('config_geral')
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clientes_phc_no'))

    op.drop_table('clientes')
    # ### end Alembic commands ###
