"""gemini_api_fields

Revision ID: 0007
Revises: 0006
Create Date: 2026-03-30 11:16:51.042709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0007'
down_revision = '0006'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('config_ia', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gemini_api_key', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('gemini_model', sa.String(length=100), nullable=True))

    with op.batch_alter_table('linhas_pedido', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'artigos_phc', ['artigo_ref'], ['referencia'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('linhas_pedido', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('config_ia', schema=None) as batch_op:
        batch_op.drop_column('gemini_model')
        batch_op.drop_column('gemini_api_key')

    # ### end Alembic commands ###
