"""notas_artigo

Revision ID: 0008
Revises: 0007
Create Date: 2026-03-31 15:13:41.666616

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0008'
down_revision = '0007'
branch_labels = None
depends_on = None


def upgrade():
    # Check if table already exists
    from sqlalchemy import inspect
    conn = op.get_bind()
    if 'notas_artigo' not in inspect(conn).get_table_names():
        op.create_table('notas_artigo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('artigo_ref', sa.String(length=50), nullable=False),
    sa.Column('texto', sa.Text(), nullable=False),
    sa.Column('criado_por', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['criado_por'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notas_artigo', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notas_artigo_artigo_ref'), ['artigo_ref'], unique=False)


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('notas_artigo', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notas_artigo_artigo_ref'))

    op.drop_table('notas_artigo')
    # ### end Alembic commands ###
