"""dashboard_layouts

Revision ID: 0009
Revises: 0008
Create Date: 2026-03-31 16:35:47.406072

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0009'
down_revision = '0008'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('config_geral', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dashboard_layouts', sa.Text(), nullable=True))


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('config_geral', schema=None) as batch_op:
        batch_op.drop_column('dashboard_layouts')

    # ### end Alembic commands ###
