"""evento_calendario

Revision ID: 0010
Revises: 0009
Create Date: 2026-03-31 16:42:41.418817

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0010'
down_revision = '0009'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eventos_calendario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('tipo', sa.String(length=30), nullable=True),
    sa.Column('data_inicio', sa.Date(), nullable=False),
    sa.Column('data_fim', sa.Date(), nullable=True),
    sa.Column('hora', sa.String(length=5), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('artigos_json', sa.Text(), nullable=True),
    sa.Column('pedido_id', sa.Integer(), nullable=True),
    sa.Column('fornecedor', sa.String(length=200), nullable=True),
    sa.Column('concluido', sa.Boolean(), nullable=True),
    sa.Column('criado_por', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['criado_por'], ['users.id'], ),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedidos_compra.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_table('eventos_calendario')
    # ### end Alembic commands ###
