"""config_phc_driver

Revision ID: 0011
Revises: 0010
Create Date: 2026-04-02 08:52:55.871125

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0011'
down_revision = '0010'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('config_phc', schema=None) as batch_op:
        batch_op.add_column(sa.Column('driver', sa.String(length=100), nullable=True))


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('config_phc', schema=None) as batch_op:
        batch_op.drop_column('driver')

    # ### end Alembic commands ###
