"""artigo_pvp_ultimo_preco

Revision ID: 0012
Revises: 0011
Create Date: 2026-04-02 09:20:17.567434

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0012'
down_revision = '0011'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artigos_phc', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pvp', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('ultimo_preco_entrada', sa.Float(), nullable=True))


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('artigos_phc', schema=None) as batch_op:
        batch_op.drop_column('ultimo_preco_entrada')
        batch_op.drop_column('pvp')

    # ### end Alembic commands ###
