"""logo_settings_chat_name

Revision ID: 0013
Revises: 0012
Create Date: 2026-04-04 10:02:52.803772

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0013'
down_revision = '0012'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('config_geral', schema=None) as batch_op:
        batch_op.add_column(sa.Column('logo_altura', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('logo_largura', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('logo_filtro', sa.String(length=100), nullable=True))


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('config_geral', schema=None) as batch_op:
        batch_op.drop_column('logo_filtro')
        batch_op.drop_column('logo_largura')
        batch_op.drop_column('logo_altura')

    # ### end Alembic commands ###
