"""reposicao_filtros

Revision ID: 0014
Revises: 0013
Create Date: 2026-04-04 10:57:23.155356

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0014'
down_revision = '0013'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('config_reposicao', schema=None) as batch_op:
        batch_op.add_column(sa.Column('min_anos_historico', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('min_meses_com_venda', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('min_total_vendido', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('ignorar_sem_movimento_anos', sa.Float(), nullable=True))


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('config_reposicao', schema=None) as batch_op:
        batch_op.drop_column('ignorar_sem_movimento_anos')
        batch_op.drop_column('min_total_vendido')
        batch_op.drop_column('min_meses_com_venda')
        batch_op.drop_column('min_anos_historico')

    # ### end Alembic commands ###
